#!/usr/bin/env node

/**
 * Icon Generation Script for LeadrScribe
 *
 * Converts the source SVG icon into all required formats and sizes using sharp library
 */

const fs = require('fs').promises;
const path = require('path');
const sharp = require('sharp');

// Paths
const SOURCE_SVG = path.join(__dirname, '..', 'assets', 'logos', 'leadrvoice_icon_2.svg');
const ICONS_DIR = path.join(__dirname, '..', 'src-tauri', 'icons');
const RESOURCES_DIR = path.join(__dirname, '..', 'src-tauri', 'resources');

// Icon size configurations
const DESKTOP_SIZES = [
  { name: '32x32.png', size: 32 },
  { name: '128x128.png', size: 128 },
  { name: '128x128@2x.png', size: 256 },
  { name: 'icon.png', size: 512 }
];

const WINDOWS_STORE_SIZES = [
  { name: 'Square30x30Logo.png', size: 30 },
  { name: 'Square44x44Logo.png', size: 44 },
  { name: 'Square71x71Logo.png', size: 71 },
  { name: 'Square89x89Logo.png', size: 89 },
  { name: 'Square107x107Logo.png', size: 107 },
  { name: 'Square142x142Logo.png', size: 142 },
  { name: 'Square150x150Logo.png', size: 150 },
  { name: 'Square284x284Logo.png', size: 284 },
  { name: 'Square310x310Logo.png', size: 310 },
  { name: 'StoreLogo.png', size: 50 }
];

const ANDROID_DENSITIES = [
  { name: 'mdpi', size: 48 },
  { name: 'hdpi', size: 72 },
  { name: 'xhdpi', size: 96 },
  { name: 'xxhdpi', size: 144 },
  { name: 'xxxhdpi', size: 192 }
];

const IOS_SIZES = [
  { name: 'AppIcon-20x20@1x.png', size: 20 },
  { name: 'AppIcon-20x20@2x.png', size: 40 },
  { name: 'AppIcon-20x20@3x.png', size: 60 },
  { name: 'AppIcon-29x29@1x.png', size: 29 },
  { name: 'AppIcon-29x29@2x.png', size: 58 },
  { name: 'AppIcon-29x29@3x.png', size: 87 },
  { name: 'AppIcon-40x40@1x.png', size: 40 },
  { name: 'AppIcon-40x40@2x.png', size: 80 },
  { name: 'AppIcon-40x40@3x.png', size: 120 },
  { name: 'AppIcon-60x60@2x.png', size: 120 },
  { name: 'AppIcon-60x60@3x.png', size: 180 },
  { name: 'AppIcon-76x76@1x.png', size: 76 },
  { name: 'AppIcon-76x76@2x.png', size: 152 },
  { name: 'AppIcon-83.5x83.5@2x.png', size: 167 },
  { name: 'AppIcon-1024x1024@1x.png', size: 1024 }
];

const TRAY_SIZES = [
  { name: 'leadrscribe.png', size: 256 },
  { name: 'tray_idle.png', size: 32 },
  { name: 'tray_idle_dark.png', size: 32 },
  { name: 'tray_recording.png', size: 32 },
  { name: 'tray_recording_dark.png', size: 32 },
  { name: 'tray_transcribing.png', size: 32 },
  { name: 'tray_transcribing_dark.png', size: 32 }
];

/**
 * Convert SVG to PNG using sharp
 */
async function convertSvgToPng(svgPath, outputPath, size) {
  await sharp(svgPath)
    .resize(size, size, {
      fit: 'contain',
      background: { r: 0, g: 0, b: 0, alpha: 0 }
    })
    .png()
    .toFile(outputPath);
}

/**
 * Generate desktop icons
 */
async function generateDesktopIcons() {
  console.log('\n📱 Generating desktop icons...');

  for (const icon of DESKTOP_SIZES) {
    const outputPath = path.join(ICONS_DIR, icon.name);
    await convertSvgToPng(SOURCE_SVG, outputPath, icon.size);
    console.log(`  ✓ ${icon.name}`);
  }
}

/**
 * Generate Windows ICO file
 */
async function generateWindowsIco() {
  console.log('\n🪟 Generating Windows ICO...');

  // Note: sharp doesn't support ICO format natively
  // Generate the largest PNG (256x256) which Tauri will convert to ICO during build
  const icoPath = path.join(ICONS_DIR, 'icon_256.png');
  await convertSvgToPng(SOURCE_SVG, icoPath, 256);

  console.log('  ✓ icon_256.png (Tauri will convert to ICO during build)');
}

/**
 * Generate macOS ICNS file
 */
async function generateMacIcns() {
  console.log('\n🍎 Generating macOS ICNS...');
  console.log('  ℹ️  ICNS will be generated by Tauri during build from icon.png');
}

/**
 * Generate Windows Store icons
 */
async function generateWindowsStoreIcons() {
  console.log('\n🏪 Generating Windows Store icons...');

  for (const icon of WINDOWS_STORE_SIZES) {
    const outputPath = path.join(ICONS_DIR, icon.name);
    await convertSvgToPng(SOURCE_SVG, outputPath, icon.size);
    console.log(`  ✓ ${icon.name}`);
  }
}

/**
 * Generate Android icons
 */
async function generateAndroidIcons() {
  console.log('\n🤖 Generating Android icons...');

  for (const density of ANDROID_DENSITIES) {
    const densityDir = path.join(ICONS_DIR, 'android', `mipmap-${density.name}`);
    await fs.mkdir(densityDir, { recursive: true });

    // Generate launcher icons
    const icons = [
      { name: 'ic_launcher.png', size: density.size },
      { name: 'ic_launcher_round.png', size: density.size },
      { name: 'ic_launcher_foreground.png', size: density.size }
    ];

    for (const icon of icons) {
      const outputPath = path.join(densityDir, icon.name);
      await convertSvgToPng(SOURCE_SVG, outputPath, icon.size);
    }

    console.log(`  ✓ mipmap-${density.name} (3 icons)`);
  }
}

/**
 * Generate iOS icons
 */
async function generateIosIcons() {
  console.log('\n📱 Generating iOS icons...');

  const iosDir = path.join(ICONS_DIR, 'ios');
  await fs.mkdir(iosDir, { recursive: true });

  for (const icon of IOS_SIZES) {
    const outputPath = path.join(iosDir, icon.name);
    await convertSvgToPng(SOURCE_SVG, outputPath, icon.size);
  }

  console.log(`  ✓ ${IOS_SIZES.length} iOS icons`);
}

/**
 * Generate tray icons
 */
async function generateTrayIcons() {
  console.log('\n🎨 Generating tray icons...');

  for (const icon of TRAY_SIZES) {
    const outputPath = path.join(RESOURCES_DIR, icon.name);
    await convertSvgToPng(SOURCE_SVG, outputPath, icon.size);
    console.log(`  ✓ ${icon.name}`);
  }

  console.log('\n  ℹ️  Note: Some tray icons may need manual tweaking:');
  console.log('      - Dark theme variants (adjust for dark backgrounds)');
  console.log('      - Recording/transcribing states (add indicators if needed)');
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 LeadrScribe Icon Generation\n');
  console.log('════════════════════════════════');

  // Check source file exists
  try {
    await fs.access(SOURCE_SVG);
    console.log(`✓ Source SVG found: ${path.basename(SOURCE_SVG)}`);
  } catch (error) {
    console.error(`❌ Source SVG not found: ${SOURCE_SVG}`);
    console.error('   Please ensure leadrvoice_icon_2.svg is in assets/logos/');
    process.exit(1);
  }

  // Ensure directories exist
  await fs.mkdir(ICONS_DIR, { recursive: true });
  await fs.mkdir(RESOURCES_DIR, { recursive: true });

  try {
    await generateDesktopIcons();
    await generateWindowsIco();
    await generateMacIcns();
    await generateWindowsStoreIcons();
    await generateAndroidIcons();
    await generateIosIcons();
    await generateTrayIcons();

    const totalIcons =
      DESKTOP_SIZES.length +
      1 + // ICO placeholder
      WINDOWS_STORE_SIZES.length +
      (ANDROID_DENSITIES.length * 3) +
      IOS_SIZES.length +
      TRAY_SIZES.length;

    console.log('\n════════════════════════════════');
    console.log(`✅ Icon generation complete!`);
    console.log(`   Total icons generated: ${totalIcons}\n`);
  } catch (error) {
    console.error('\n❌ Error generating icons:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

main();
